apiVersion: v1
kind: Service
metadata:
  name: laravel
spec:
  type: ClusterIP #NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: laravel
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  labels:
    app: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      name: laravel
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: <image registry>
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "100Gi"
              cpu: "100m"
          envFrom:
            - configMapRef:
                name: laravel

      imagePullSecrets:
            - name: secrets
